# Generated by Django 3.2.3 on 2021-05-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicyo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='demo@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
